### ISSUE TITLE
One more backend: consul

### ISSUE THREAD

**Issue by hassila** [apple/swift-service-discovery#49]
We have just opened sourced our backend for consul, initial implementation here:

https://github.com/ordo-one/package-consul

**Comment by tomerd** [comment]
should we add to the readme?

**Comment by tomerd** [comment]
also since you now have practical experience with thew API, any opinions on https://github.com/apple/swift-service-discovery/pull/45?

**Comment by hassila** [comment]
Yes please!

**Comment by hassila** [comment]
> also since you now have practical experience with thew API, any opinions on #45?

Let me ask the engineer who worked on it to come back on this
